syntax = "proto3";

package task_v1;

import "google/protobuf/timestamp.proto";

option go_package = "bernard/task-service/pkg;task_v1";

message Task {
  int64 task_id = 1;
  string name = 2;
  optional string description = 3;
  repeated Tag tags = 4;
  optional int32 priority = 5;
  optional string status = 6;

  google.protobuf.Timestamp start_time = 7;
  google.protobuf.Timestamp deadline = 8;

  optional int64 group_id = 9;
  optional int64 project_id = 10;
  string user_id = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  bool is_archived = 14;
}

message Tag {
  int64 id = 1;
  string name = 2;
  string color = 3;
  string user_id = 4;
  int64 project_id = 5;
}

message Group {
  int64 id = 1;
  string name = 2;
  repeated Task tasks = 3;
  int64 task_count = 4;
  int64 project_id = 5;
}

message Project {
  int64 id = 1;
  string name = 2;
  optional string description = 3;
  repeated Group groups = 4;
  int64 task_count = 5;
  string user_id = 6;
}

service TaskService {
  rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse);
  rpc UpdateTask(UpdateTaskRequest) returns (UpdateTaskResponse);
  rpc DeleteTask(DeleteTaskRequest) returns (DeleteTaskResponse);
  rpc GetTask(GetTaskRequest) returns (GetTaskResponse);
  rpc GetListTask(GetListTaskRequest) returns (GetListTaskResponse);
  rpc GetGroupTasks(GetGroupTasksRequest) returns (GetGroupTasksResponse);

  rpc ArchiveTask(ArchiveTaskRequest) returns (ArchiveTaskResponse);

  rpc CreateTag(CreateTagRequest) returns (CreateTagResponse);
  rpc UpdateTag(UpdateTagRequest) returns (UpdateTagResponse);
  rpc DeleteTag(DeleteTagRequest) returns (DeleteTagResponse);
  rpc GetTag(GetTagRequest) returns (GetTagResponse);
  rpc GetTagList(GetTagListRequest) returns (GetTagListResponse);
  rpc GetTaskTags(GetTaskTagsRequest) returns (GetTaskTagsResponse);

  rpc AddTagsToTask(AddTagsToTaskRequest) returns (AddTagsToTaskResponse);
  rpc RemoveTagsFromTask(RemoveTagsFromTaskRequest) returns (RemoveTagsFromTaskResponse);
  rpc RemoveAllTagsFromTask(RemoveAllTagsFromTaskRequest) returns (RemoveAllTagsFromTaskResponse);

  rpc CreateGroup(CreateGroupRequest) returns (CreateGroupResponse);
  rpc UpdateGroup(UpdateGroupRequest) returns (UpdateGroupResponse);
  rpc DeleteGroup(DeleteGroupRequest) returns (DeleteGroupResponse);
  rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);
  rpc GetProjectGroups(GetProjectGroupsRequest) returns (GetProjectGroupsResponse);

  rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse);
  rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse);
  rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse);
  rpc GetProjects(GetProjectsRequest) returns (GetProjectsResponse);
  rpc GetProject(GetProjectRequest) returns (GetProjectResponse);
}

message CreateTaskRequest {
  string name = 1;
  optional string description = 2;
  repeated int64 tag_ids = 3;
  optional int32 priority = 4;
  optional string status = 5;
  optional int64 group_id = 6;
  optional int64 project_id = 7;

  google.protobuf.Timestamp start_time = 8;
  google.protobuf.Timestamp deadline = 9;
}

message CreateTaskResponse {
  Task task = 1;
}

message UpdateTaskRequest {
  int64 task_id = 1;
  optional string name = 2;
  optional string description = 3;
  repeated int64 tag_ids = 4;
  optional int32 priority = 5;
  optional string status = 6;
  optional int64 group_id = 7;
  optional int64 porject_id = 8;

  google.protobuf.Timestamp start_time = 9;
  google.protobuf.Timestamp deadline = 10;
}

message UpdateTaskResponse {
  Task task = 1;
}

message DeleteTaskRequest {
  int64 task_id = 1;
}

message DeleteTaskResponse {
  bool success = 1;
}

message GetTaskRequest {
  int64 task_id = 1;
}

message GetTaskResponse {
  Task task = 1;
}

message GetListTaskRequest {
  optional int32 priority = 1;
  optional int64 tag_ids = 2;
  google.protobuf.Timestamp from = 3;
  google.protobuf.Timestamp to = 4;
  uint64 limit = 5;
  uint64 offset = 6;
}

message GetListTaskResponse {
  repeated Task tasks = 1;
}

message GetGroupTasksRequest {
  int64 group_id = 1;
  string user_id = 2;
  uint64 limit = 3;
  uint64 offset = 5;
}

message GetGroupTasksResponse {
  repeated Task tasks = 1;
}

message ArchiveTaskRequest {
  int64 task_id = 1;
}

message ArchiveTaskResponse {
  Task task = 1;
}

message CreateTagRequest {
  string name = 1;
  string color = 2;
  int64 project_id = 3;
}

message CreateTagResponse {
  Tag tag = 1;
}

message UpdateTagRequest {
  int64 id = 1;
  optional string name = 2;
  optional string color = 3;
}

message UpdateTagResponse {
  Tag tag = 1;
}

message DeleteTagRequest {
  int64 id = 1;
}

message DeleteTagResponse {
  bool success = 1;
}

message GetTagRequest {
  int64 id = 1;
}

message GetTagResponse {
  Tag tag = 1;
}

message GetTagListRequest {
  int64 project_id = 1;
  uint64 limit = 2;
  uint64 offset = 3;
}

message GetTagListResponse {
  repeated Tag tags = 1;
}

message GetTaskTagsRequest {
    int64 task_id = 1;
}

message GetTaskTagsResponse {
    repeated Tag tags = 1;
}

message AddTagsToTaskRequest {
  int64 task_id = 1;
  repeated int64 tags_ids = 2;
}

message AddTagsToTaskResponse {
    bool succes = 1;
}

message RemoveTagsFromTaskRequest {
    int64 task_id = 1;
    repeated int64 tags_ids = 2;
}

message RemoveTagsFromTaskResponse {
    bool success = 1;
}

message RemoveAllTagsFromTaskRequest {
    int64 task_id = 1;
}

message RemoveAllTagsFromTaskResponse {
    bool success = 1;
}

message CreateGroupRequest {
  string name = 1;
  int64 project_id = 2;
}

message CreateGroupResponse {
  Group group = 1;
}

message UpdateGroupRequest {
  int64 id = 1;
  optional string name = 2;
  optional int64 project_id = 3;
}

message UpdateGroupResponse {
  Group group = 1;
}

message DeleteGroupRequest {
  int64 id = 1;
}

message DeleteGroupResponse {
  bool success = 1;
}

message GetGroupRequest {
    int64 group_id = 1;
    uint64 limit = 2;
    uint64 offset = 3;
}

message GetGroupResponse {
    Group group = 1;
}

message GetProjectGroupsRequest {
    int64 project_id = 1;
    uint64 limit = 2;
    uint64 offset = 3;
}

message GetProjectGroupsResponse {
    repeated Group groups = 1;
}

message CreateProjectRequest {
  string name = 1;
  optional string description = 2;
}

message CreateProjectResponse {
  Project project = 1;
}

message UpdateProjectRequest {
  int64 id = 1;
  optional string name = 2;
  optional string description = 3;
}

message UpdateProjectResponse {
  Project project = 1;
}

message DeleteProjectRequest {
  int64 id = 1;
}

message DeleteProjectResponse {
  bool success = 1;
}

message GetProjectRequest {
    int64 project_id = 1;
    uint64 limit = 3;
    uint64 offset = 4;
}

message GetProjectResponse {
  Project project = 1;
}

message GetProjectsRequest {
    uint64 limit = 1;
    uint64 offset = 2;
}

message GetProjectsResponse {
    repeated Project projects = 1;
}
