// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: users.internal.proto

package user_internal_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_users_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_internal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserProfileRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *CreateUserProfileRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResponse) Reset() {
	*x = CreateUserProfileResponse{}
	mi := &file_users_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResponse) ProtoMessage() {}

func (x *CreateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_users_internal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileRequest) Reset() {
	*x = DeleteUserProfileRequest{}
	mi := &file_users_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileRequest) ProtoMessage() {}

func (x *DeleteUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_internal_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileResponse) Reset() {
	*x = DeleteUserProfileResponse{}
	mi := &file_users_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileResponse) ProtoMessage() {}

func (x *DeleteUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_users_internal_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_users_internal_proto protoreflect.FileDescriptor

const file_users_internal_proto_rawDesc = "" +
	"\n" +
	"\x14users.internal.proto\x12\x11users_internal_v1\"\xa9\x01\n" +
	"\x18CreateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezoneB\t\n" +
	"\a_status\"4\n" +
	"\x19CreateUserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x18DeleteUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x19DeleteUserProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf6\x01\n" +
	"\x14UsersInternalService\x12n\n" +
	"\x11CreateUserProfile\x12+.users_internal_v1.CreateUserProfileRequest\x1a,.users_internal_v1.CreateUserProfileResponse\x12n\n" +
	"\x11DeleteUserProfile\x12+.users_internal_v1.DeleteUserProfileRequest\x1a,.users_internal_v1.DeleteUserProfileResponseBMZKgithub.com/bernard-app/bernard-protos/pkg/user_internal_v1;user_internal_v1b\x06proto3"

var (
	file_users_internal_proto_rawDescOnce sync.Once
	file_users_internal_proto_rawDescData []byte
)

func file_users_internal_proto_rawDescGZIP() []byte {
	file_users_internal_proto_rawDescOnce.Do(func() {
		file_users_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_internal_proto_rawDesc), len(file_users_internal_proto_rawDesc)))
	})
	return file_users_internal_proto_rawDescData
}

var file_users_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_users_internal_proto_goTypes = []any{
	(*CreateUserProfileRequest)(nil),  // 0: users_internal_v1.CreateUserProfileRequest
	(*CreateUserProfileResponse)(nil), // 1: users_internal_v1.CreateUserProfileResponse
	(*DeleteUserProfileRequest)(nil),  // 2: users_internal_v1.DeleteUserProfileRequest
	(*DeleteUserProfileResponse)(nil), // 3: users_internal_v1.DeleteUserProfileResponse
}
var file_users_internal_proto_depIdxs = []int32{
	0, // 0: users_internal_v1.UsersInternalService.CreateUserProfile:input_type -> users_internal_v1.CreateUserProfileRequest
	2, // 1: users_internal_v1.UsersInternalService.DeleteUserProfile:input_type -> users_internal_v1.DeleteUserProfileRequest
	1, // 2: users_internal_v1.UsersInternalService.CreateUserProfile:output_type -> users_internal_v1.CreateUserProfileResponse
	3, // 3: users_internal_v1.UsersInternalService.DeleteUserProfile:output_type -> users_internal_v1.DeleteUserProfileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_internal_proto_init() }
func file_users_internal_proto_init() {
	if File_users_internal_proto != nil {
		return
	}
	file_users_internal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_internal_proto_rawDesc), len(file_users_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_internal_proto_goTypes,
		DependencyIndexes: file_users_internal_proto_depIdxs,
		MessageInfos:      file_users_internal_proto_msgTypes,
	}.Build()
	File_users_internal_proto = out.File
	file_users_internal_proto_goTypes = nil
	file_users_internal_proto_depIdxs = nil
}
