syntax = "proto3";

package users_v1;

option go_package = "bernard/user-service/pkg;users_v1";

message User {
    string id = 1;
    string email = 2;
    string username = 3;
    string status = 4;
}

message Settings {
    string user_id = 1;
    int32 theme = 2;
    string timezone = 3;
    string lang = 4;
}

service UserService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
    rpc UpdateUserStatus(UpdateUserStatusRequest) returns (UpdateUserStatusResponse);
    rpc SoftDeleteUser(SoftDeleteUserRequest) returns (SoftDeleteUserResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
    rpc GetUsersList(GetUsersListRequest) returns (GetUsersListResponse);
    
    rpc UpdateSettings(UpdateSettingsRequest) returns (UpdateSettingsResponse);
    rpc GetSettings(GetSettingsRequest) returns (GetSettingsResponse);
}

message CreateUserRequest {
    string email = 1;
    string username = 2; 
    optional string status = 3;
}

message CreateUserResponse {
    User user = 1;
}

message UpdateUserRequest {
    optional string email = 1;
    optional string username = 2;
}

message UpdateUserResponse {
    User user = 1;
}

message UpdateUserStatusRequest {
    optional string status = 1;
}

message UpdateUserStatusResponse {
    User user = 1;
}

message SoftDeleteUserRequest {
}

message SoftDeleteUserResponse {
    bool success = 1;
}

message GetUserRequest {
}

message GetUserResponse {
    User user = 1;
}

message GetUsersListRequest {
    uint64 limit = 1;
    uint64 offset = 2;
}

message GetUsersListResponse {
    repeated User user = 1;
}

message UpdateSettingsRequest {
    optional int32 theme = 1;
    optional string timezone = 2;
    optional string lang = 3;
}

message UpdateSettingsResponse {
    Settings settings = 1;
}

message GetSettingsRequest {
}

message GetSettingsResponse {
    Settings settings = 1;
}